---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    env:
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      - uses: actions/checkout@v1
      - run: docker build .
